# Generated by Django 4.0.1 on 2022-02-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque_restante',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
